config/routes.rb
Rails.application.routes.draw do
  # Change /users/ to /doctors/
  resources :users, path: 'doctors' do
    resources :patients do
      resources :patient_notes, :medications
    end
  end
  resources :sessions, :hospitals, :doctorlists

  # define root page
  root 'pages#index'

  get 'error' => 'pages#errorpage'

  get 'signup' => 'users#new'

  get 'registeradmin' => 'users#newadmin'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'dashboard' => 'users#dashboard'

  get 'users/:id/export' => 'users#exportjson'

  get 'patient/:id/import' => 'patients#importpatient'
  post 'patient/:id/import' => 'patients#importpatient'

  get 'importui' => 'patients#importsearch'

  get 'patientindex' => 'patients#adminindex'

  get 'autherror' => 'pages#auth_error'

  get ':invalid' => 'pages#errorpage'
end

app/models/user.rb
class User < ApplicationRecord
  # bcrypt gem
  has_secure_password
  has_secure_token :auth_token
  attr_encrypted_options[encode: true]
  # Encrypt data
  attr_encrypted :name, key: Rails.application.secrets.encr_key

  has_many :patients
  has_many :doctorlists
  has_many :hospitals, through: :doctorlists

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: %w[new create newadmin]

  def new
    @page_title = 'Register'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = 'Edit Account'
    if User.exists?(params[:id])
      @user = User.find(params[:id])
      if @user != current_user
        redirect_to '/'
      end
    else
      redirect_to '/'
    end
  end

  def index
    @page_title = 'Users Index'
    @users = User.paginate(page: params[:page], per_page: 30)
    if params[:search]
      @users = User.where(id: params[:search]).order('created_at DESC').paginate(page: params[:page], per_page: 30)
      if params[:search].blank?
        @users = User.paginate(page: params[:page], per_page: 30).order('created_at DESC')
      end
    end
    respond_to do |f|
      f.html {
      }

      f.any(:xml, :json) {
        render request.format.to_sym => @users
      }
    end
  end

  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  # User's custom dashboard
  def dashboard
    @page_title = 'Dashboard'
    @patients = current_user.patients.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    if User.exists?(params[:id])
      @user = User.find(params[:id])
      @page_title = @user.name
      @doctorlists = @user.doctorlists
    else
      redirect_to root_path
    end
    respond_to do |f|
      f.html {
      }
      f.any(:xml, :json) {
        render request.format.to_sym => @user
      }
    end
  end

  # Register new admin user (admin: true)
  def newadmin
    @page_title = 'Register Admin'
    @user = User.new
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :auth_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admindash.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= current_user.name %>'s Dashboard</h1>
    <hr />
    <p><%= link_to 'Your Profile', current_user %></p>
  </div>

  <div class="col-md-3">
    <div class="dashpanel">
      <div class="page-header">
        <h2>Users <i class="fa fa-user-md"></i></h2>
      </div>
      <p>There are <%= link_to "#{User.count} registered Users.", users_path %></p>
    </div>
  </div>
  <div class="col-md-3">
    <div class="dashpanel">
      <div class="page-header">
        <h2>Patients <i class="fa fa-medkit" aria-hidden="true"></i></h2>
      </div>
      <p>There are <%= link_to "#{Patient.count} registered Patients.", patientindex_path %></p>
    </div>
  </div>
  <div class="col-md-3">
    <div class="dashpanel">
      <div class="page-header">
        <h2>Hospitals <i class="fa fa-hospital-o" aria-hidden="true"></i></h2>
      </div>
      <p>There are <%= link_to "#{Hospital.count} registered Hospitals.", hospitals_path %></p>
    </div>
  </div>

  <div class="col-md-3">
    <div class="dashpanel">
      <div class="page-header">
        <h2>Registrations <i class="fa fa-link" aria-hidden="true"></i></h2>
      </div>
      <p>There are <%= link_to "#{Doctorlist.count} registered associtations.", doctorlists_path(context: "admin") %></p>
    </div>
  </div>
</div>

app/views/users/_adminnav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="border-right: 1px solid;">ChartPort MD
        <i class="fa fa-heartbeat" aria-hidden="true"></i></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Users
            <i class="fa fa-user-md" aria-hidden="true"></i>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index", users_path %></li>
            <li><%= link_to "Export JSON", controller: 'users', action: 'index', format: 'json' %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Patients
          <i class="fa fa-medkit" aria-hidden="true"></i>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index/Search", controller: :patients, action: :adminindex %></li>
            <li><%= link_to "JSON Export", controller: 'patients', action: 'adminindex', format: 'json' %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Hospitals
          <i class="fa fa-hospital-o" aria-hidden="true"></i>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Search Hospitals", hospitals_path %></li>
            <li><%= link_to "New Hospital", new_hospital_path %></li>
            <li><%= link_to "Export JSON", controller: 'hospitals', action: 'index', format: 'json' %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign Out", logout_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_userdash.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= current_user.name %>'s Dashboard</h1>
    <hr />
    <p><%= link_to 'Your Profile', current_user %></ps>
  </div>

  <div class="page-header">
    <h1>Recent Patients (Last 24 Hours)</h1>
  </div>
  <div class="col-md-6">
    <button class="btn btn-default"><%= link_to "New Patient", new_user_patient_path(current_user) %> <span class="glyphicon glyphicon-pencil"></button>
  </div>
  <div class="col-md-6">
    <button class="btn btn-default"><%= link_to "Search My Database", user_patients_path(current_user) %> <span class="glyphicon glyphicon-list"></span></button>
  </div>
  <br />
  <%= render "patients/patientsindex" %>
</div>

app/views/users/_usernav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="border-right: 1px solid;">ChartPort MD
        <i class="fa fa-heartbeat" aria-hidden="true"></i></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Users
          <i class="fa fa-user-md" aria-hidden="true"></i>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index", users_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Patients
          <i class="fa fa-medkit" aria-hidden="true"></i>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Patients", user_patients_path(current_user) %></li>
            <li><%= link_to "New", new_user_patient_path(current_user) %></li>
            <li><%= link_to "Import Patient UI", importui_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Hospitals
          <i class="fa fa-hospital-o" aria-hidden="true"></i>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Search Hospitals", hospitals_path %></li>
            <li><%= link_to "My Registrations", doctorlists_path(:context => "user", :given_id => current_user.id) %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign Out", logout_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/dashboard.html.erb
<% if current_user.admin %>
  <%= render "users/admindash" %>
<% else %>
  <%= render "users/userdash" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

<div class="container">
  <div class="jumbotron">
    <h2>Edit Account</h2>
    <hr />
    <h1><%= @user.name %></h1>
  </div>
</div>

<div class="errors">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="page-header">
    <h3>Email ID:</h3>
  </div>
  <%= f.text_field :email, :class => 'textfield' %>
</div>


<div class="container">
  <div class="page-header">
    <h3>Enter Password to confirm changes:</h3>
  </div>
  <%= f.password_field :password, :class => 'textfield' %>
</div>

<br />

<%= button_tag(type: 'submit', class: "btn btn-default") do %>
 Update Record <span class="glyphicon glyphicon-floppy-disk"></span>
<% end %>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Users Index</h1>
  </div>
</div>
<% if @users.any? %>

<br />

  <div class="container">

  <%= form_tag(users_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
      <%= submit_tag "Search", :name => nil, :class => "btn btn-default"%>
  <% end %>
  <br />

    <div class="page-header">
      <h3>Search Results</h3>
    </div>
  </div>

  <% @users.each do |user| %>

  <div class="hovertip"><%= link_to user.name, user %><% if user.id == current_user.id %><small> (You)</small><% end %>
    <span class="hovertiptext"><%= user.name %><br />
      Email: <%= user.email %>
      <% if user.admin %><br /><small>admin</small><% end %>
     </span>
  </div>
  <br />

  <% end %>

  <div class="digg_pagination">
    <%= will_paginate @users %>
  </div>

<% else %>

  <div class="container">
    <div class="page-header">
      <h3>Search Results</h3>
    </div>
    <p>No users could be found.</p>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Sign Up</h1>
    <hr />
    <h2>New Medical Professional</h2>
  </div>
</div>

<div class="container">
    <% if @user.errors.any? %>
      <div class="page-header">
        <h2><%= pluralize(@user.errors.count, "error") %></h2>
      </div>
      <% @user.errors.full_messages.each do |msg| %>
        <p>
          <%= msg %>
        </p>
      <% end %>
  <% end %>
</div>


<div class="container">
  <%= form_for @user do |f| %>
  <p>
    <%= f.label "Name" %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label "Email" %><br />
    <%= f.email_field :email %>
  </p>

  <%= f.check_box :admin, {checked: false, style: "display:none;"}%>

  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <%= button_tag(type: 'submit', class: "btn btn-default") do %>
   Register <i class="fa fa-plus"></i>
  <% end %>

  <% end %>
</div>

app/views/users/newadmin.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Sign Up</h1>
    <hr />
    <h2>New Admin</h2>
  </div>
</div>

<div class="container">
    <% if @user.errors.any? %>
      <div class="page-header">
        <h2><%= pluralize(@user.errors.count, "error") %></h2>
      </div>
      <% @user.errors.full_messages.each do |msg| %>
        <p>
          <%= msg %>
        </p>
      <% end %>
  <% end %>
</div>


<div class="container">
  <%= form_for @user do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>

  <%= f.check_box :admin, {checked: true, style: "display:none"}%>

  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <%= button_tag(type: 'submit', class: "btn btn-default") do %>
   Register <i class="fa fa-plus"></i>
  <% end %>
  
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= @user.name %></h1>
    <p>ChartPort MD join date: <%= @user.created_at.strftime("%b %e, %Y") %></p>
  </div>
  <% if current_user.admin %>
  <p><%= link_to "JSON Export", controller: 'users', action: 'show', id: @user.id, format: 'json' %></p>
  <% end %>

  <% if @user.admin %>
  <p>This user is an admin.</p>
  <% else %>
  <div class="page-header">
    <h2>Hospital Registrations</h2>
  </div>
  <%= render "doctorlists/userindex" %>
  <% end %>
</div>