config/routes.rb
Rails.application.routes.draw do
  # Change /users/ to /doctors/
  resources :users, path: 'doctors' do
    resources :patients do
      resources :patient_notes, :medications
    end
  end
  resources :sessions, :hospitals, :doctorlists

  # define root page
  root 'pages#index'

  get 'error' => 'pages#errorpage'

  get 'signup' => 'users#new'

  get 'registeradmin' => 'users#newadmin'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'dashboard' => 'users#dashboard'

  get 'users/:id/export' => 'users#exportjson'

  get 'patient/:id/import' => 'patients#importpatient'
  post 'patient/:id/import' => 'patients#importpatient'

  get 'importui' => 'patients#importsearch'

  get 'patientindex' => 'patients#adminindex'

  get 'autherror' => 'pages#auth_error'

  get ':invalid' => 'pages#errorpage'
end

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="border-right: 1px solid;">MedLog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <% if !current_user.admin %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Patients <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Patient Search", patients_path %></li>
              <li><%= link_to "New Patient Registry", new_patient_path %></li>
            </ul>
          </li>
          <% end %>
        <% else %>
          <li><%= link_to 'About', controller: 'pages', action: 'about'%></li>
        <% end %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
              <li><%= link_to "Sign Out", logout_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Portal <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Log In", login_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Admin Singup", registeradmin_path %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/_no_user_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ChartPort MD
        <i class="fa fa-heartbeat" aria-hidden="true"></i></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Portal
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Log In", login_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/auth_error.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Uh Oh!</h1>
    <p>
      No User was found with your email/password.
      <%= link_to 'Try Again?', login_path %>
    </p>
  </div>
</div>

app/views/pages/errorpage.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>It seems something's gone wrong.</h1>
    <p>
      Try returning <%= link_to 'Home', root_path %>!
    </p>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container-fluid">
  <div id="top">
    <div class="jumbotron">
      <h1>ChartPort M.D.</h1>
      <p>A cloud-based solution for maintaining patient health records.</p>
    </div>
  </div>

  <div id="mission">
    <div class="page-header">
      <h2>Our Mission</h2>
    </div>
    <div class="container">
      <p>
        At its core, ChartPort exists to streamline doctor-patient
        interactions to help bring healthcare into the modern digital age.
      </p>
      <p>
        Through our platform, doctors can easily create, view, or edit records about
        patients they see.  Our hope is to minimize time healthcare professionals
        spend doing paperwork and maximize time spent tending to patients, giving them
        the care they need.
      </p>
      <p>
        In addition, ChartPort allows easy transferral of patient records between medical
        professionals and facilitites.  In dire situations, we can help alleviate guesswork
        by providing an easy, extensive record for a patient.
      </p>
    </div>
  </div>

  <div id="features">
    <div class="page-header">
      <h2>ChartPort Features</h2>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-5" id="box">
          <div class="page-header">
            <h3>Accounts <i class="fa fa-users"></i></h3>
          </div>
          <p>
            ChartPort MD features support for two types of user accounts, medical professionals and administrators.
          </p>
        </div>
        <div class="col-sm-2"></div>
        <div class="col-sm-5" id="box">
          <div class="page-header">
            <h3>Patient Records <i class="fa fa-address-card"></i></h3>
          </div>
          <p>
            Extensive record keeping, including contact information, notes from appointments,
            and prescription information.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5" id="box">
          <div class="page-header">
            <h3>Hospital Registry <i class="fa fa-hospital-o"></i></h3>
          </div>
          <p>
            A registry of hospitals using ChartPort, maintained by administrators.
            Medical accounts can register to each hospital.  All hospital pages include
            Google Maps support for geolocation.
          </p>
        </div>
        <div class="col-sm-2"></div>
        <div class="col-sm-5" id="box">
          <div class="page-header">
            <h3>Encryption <i class="fa fa-user-secret"></i></h3>
          </div>
          <p>
            ChartPort features extensive encryption of its data- allowing data privacy
            for both you and your patients.
          </p>
        </div>
      </div>
    </div>
  </div>