config/routes.rb
Rails.application.routes.draw do
  # Change /users/ to /doctors/
  resources :users, path: 'doctors' do
    resources :patients do
      resources :patient_notes, :medications
    end
  end
  resources :sessions, :hospitals, :doctorlists

  # define root page
  root 'pages#index'

  get 'error' => 'pages#errorpage'

  get 'signup' => 'users#new'

  get 'registeradmin' => 'users#newadmin'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'dashboard' => 'users#dashboard'

  get 'users/:id/export' => 'users#exportjson'

  get 'patient/:id/import' => 'patients#importpatient'
  post 'patient/:id/import' => 'patients#importpatient'

  get 'importui' => 'patients#importsearch'

  get 'patientindex' => 'patients#adminindex'

  get 'autherror' => 'pages#auth_error'

  get ':invalid' => 'pages#errorpage'
end

app/models/patient_note.rb
class PatientNote < ApplicationRecord
  attr_encrypted_options.merge!(:encode => true)

  # Encrypt data
  attr_encrypted :note, key: Rails.application.secrets.encr_key

  belongs_to :patient
end

app/controllers/patient_notes_controller.rb
class PatientNotesController < ApplicationController
  before_action :require_user

  def new
    @page_title = "New Patient Note"
    @user = current_user
    @patient = Patient.find(params[:patient_id])
    @patient_note = PatientNote.new
  end

  def create
    @page_title = "New Patient Note"
    @patient = Patient.find(params[:patient_id])
    @user = current_user
    @patient_note = @patient.patient_notes.new(patient_note_params)
    if @patient_note.save
      @patient.touch
      redirect_to user_patient_path(current_user, @patient)
    else
      render 'new'
    end
  end

  def edit
    @page_title = "Edit Note"
    if PatientNote.exists?(params[:id])
      @patient_note = PatientNote.find(params[:id])
      @patient = Patient.find(@patient_note.patient_id)
      @user = current_user
      if @patient_note.user_id != @user.id
        redirect_to patient_path(@patient)
      end
    end
  end

  def show
    @page_title = "Show Note"
    if PatientNote.exists?(params[:id])
      @patient_note = PatientNote.find(params[:id])
      @patient = Patient.find(@patient_note.patient_id)
      @user = User.find(@patient_note.user_id)
    end
  end

  def update
    @patient_note = PatientNote.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    if @patient_note.update(patient_note_params)
      @patient.touch
      redirect_to patient_path(@patient)
    else
      render 'edit'
    end
  end

  def destroy
    @patient_note = PatientNote.find(params[:id])
    @patient = Patient.find(@patient_note.patient_id)
    @patient_note.destroy
    @patient.touch

    redirect_to patient_path(@patient)
  end

  private

  def patient_note_params
    params.require(:patient_note).permit(:note, :user_id, :patient_id)
  end
end

app/helpers/patient_notes_helper.rb
module PatientNotesHelper
end

app/views/patient_notes/_index.html.erb
<% if @patient_notes.any? %>
  <% @patient_notes.reverse_each do |patient_note| %>
    <div class="row">
      <div class="col-sm-1"></div>
      <div class="col-sm-3">
        <h4>Date Created</h4>
        <p>
          <%= patient_note.created_at.strftime('%B %d, %Y') %>
        </p>
      </div>
      <div class="col-sm-4">
        <h4>Note</h4>
        <p>
          <%= truncate(patient_note.note, length: 75) %>
          <% if patient_note.note.length >= 75 %>
          <small><%= link_to "Show Full", patient_note_path(patient_note) %></small>
          <% end %>
        </p>
      </div>
      <div class="col-sm-3">
        <h4>Physician</h4>
        <p>
          <%= link_to User.find(patient_note.user_id).name, user_path(User.find(patient_note.user_id)) %>
        </p>
      </div>
      <div class="col-sm-1"></div>
      <% if User.find(@patient.user_id) == current_user.id || User.find(@patient.primary_care_physician) == current_user %>
      <h4>Actions</h4>
      <small><%= link_to "Edit", edit_user_patient_patient_note_path(current_user, @patient, patient_note) %></small><br />
      <small><%= link_to "Delete", user_patient_patient_note_path(current_user, @patient, patient_note), method: :delete %></small><br />
      <% end %>
    </div>
  <% end %>

  <div class="digg_pagination">
    <%= will_paginate @patient_notes %>
  </div>

<% else %>
  <h5><%= @patient.name %> Currently has no associated notes.</h5>
<% end %>

app/views/patient_notes/edit.html.erb
<%= form_for @patient_note do |f| %>

<div class="container">
  <div class="jumbotron">
    <h1>Patient Notes</h1>
    <hr />
    <small><%= @patient.name %></small>
  </div>

  <% if @patient_note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient_note.errors.count, "error") %>
      </h2>
        <% @patient_note.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
    </div>
  <% end %>

  <div class="page-header">
    <h2>Notes:</h2>
  </div>
  <p><%= f.text_area :note, class: 'textbox' %></p>

  <p>
    <%= hidden_field_tag(:patient_id, @patient.id) %>
    <%= f.text_field :user_id, value: @user.id, style: "display: none;" %>
    <%= button_tag(type: 'submit', class: "btn btn-default") do %>
     Submit Note <i class="fa fa-plus"></i>
    <% end %>
  </p>

</div>

<% end %>

app/views/patient_notes/new.html.erb
<%= form_for @patient_note, url: user_patient_patient_notes_path(current_user, @patient) do |f| %>

<div class="container">
  <div class="jumbotron">
    <h1>Patient Notes</h1>
    <hr />
    <small><%= @patient.name %></small>
  </div>

  <% if @patient_note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient_note.errors.count, "error") %>
      </h2>
        <% @patient_note.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
    </div>
  <% end %>

  <div class="page-header">
    <h2>Notes:</h2>
  </div>
  <p><%= f.text_area :note, class: 'textbox' %></p>

  <p>
    <%= hidden_field_tag(:patient_id, @patient.id) %>
    <%= f.text_field :user_id, value: @user.id, style: "display: none;" %>
    <%= button_tag(type: 'submit', class: "btn btn-default") do %>
     Submit Note <i class="fa fa-plus"></i>
    <% end %>
  </p>

</div>

<% end %>

app/views/patient_notes/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= "#{@patient.name} Note" %></h1>
  </div>

  <div class="page-header">
    <h2>Note Text:</h2>
  </div>
  <p>
    <%= @patient_note.note %>
  </p>

  <div class="page-header">
    <h2>Date:</h2>
  </div>
  <p>
    <%= @patient_note.created_at.strftime("%B %d, %Y") %>
  </p>

  <div class="page-header">
    <h2>Submitted by: </h2>
  </div>
  <p>
    <%= link_to @user.name, user_path(@user) %>
  </p>

  <br />
  
  <%= button_to "Return to Patient", patient_path(@patient), method: 'get', :class => "btn btn-default" %>
</div>