config/routes.rb
Rails.application.routes.draw do
  # Change /users/ to /doctors/
  resources :users, path: 'doctors' do
    resources :patients do
      resources :patient_notes, :medications
    end
  end
  resources :sessions, :hospitals, :doctorlists

  # define root page
  root 'pages#index'

  get 'error' => 'pages#errorpage'

  get 'signup' => 'users#new'

  get 'registeradmin' => 'users#newadmin'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'dashboard' => 'users#dashboard'

  get 'users/:id/export' => 'users#exportjson'

  get 'patient/:id/import' => 'patients#importpatient'
  post 'patient/:id/import' => 'patients#importpatient'

  get 'importui' => 'patients#importsearch'

  get 'patientindex' => 'patients#adminindex'

  get 'autherror' => 'pages#auth_error'

  get ':invalid' => 'pages#errorpage'
end

app/models/patient.rb
class Patient < ApplicationRecord
  attr_encrypted_options.merge!(:encode => true)

  # Encrypt data
  attr_encrypted :name, key: Rails.application.secrets.encr_key
  attr_encrypted :date_of_birth, key: Rails.application.secrets.encr_key
  attr_encrypted :phone_number, key: Rails.application.secrets.encr_key

  belongs_to :user
  has_many :medications
  has_many :patient_notes

  validates :name, presence: true
  validates :date_of_birth, presence: true
  validates :phone_number, presence: true
  
  # transfer active user/doctor to new user
  def transfer(user)
    self.update(:user_id => user.id)
  end

  # Find age (for show and hovertip)
  def find_age
    dob = self.date_of_birth.to_date
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :require_user

  def new
    @page_title = 'Add Patient Record'
    @patient = Patient.new
    @user = current_user
  end

  def create
    @patient = current_user.patients.new(patient_params)
    if @patient.save
      redirect_to user_patient_path(current_user, @patient)
    else
      render 'new'
    end
  end

  def edit
    @page_title = 'Edit Patient'
    if Patient.exists?(params[:id])
      @patient = current_user.patients.find(params[:id])
      if @patient.user_id != current_user.id
        redirect_to user_patient_path(@patient.user, @patient)
      end
    end
  end

  def update
    @patient = current_user.patients.find(params[:id])
    if @patient.update(patient_params)
      redirect_to user_patient_path(@patient.user, @patient)
    else
      render 'edit'
    end
  end

  def show
    user = User.find(params[:user_id])
    @patient = user.patients.find(params[:id])
    @page_title = @patient.name + " record"
    @patient_notes = @patient.patient_notes.paginate(:page => params[:page], :per_page => 15)
    @medications = @patient.medications.paginate(:page => params[:page], :per_page => 10)

    respond_to do | f |
      f.html {
      }

      f.any(:xml, :json) {
        render request.format.to_sym => @patient
      }
    end
  end

  def index
    @page_title = 'Patients Index'
    @patients = current_user.patients.paginate(:page => params[:page], :per_page => 10)
    if params[:search]
      @patients = current_user.patients.where(id: params[:search]).paginate(:page => params[:page], :per_page => 30)
      if params[:search].blank?
        @patients = current_user.patients.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
      end
    end
    respond_to do |f|
      f.html {
      }

      f.any(:xml, :json) {
        render request.format.to_sym => @patients
      }
    end
  end

  # Show all patients
  def adminindex
    @page_title = 'Patients Index'
    @patients = Patient.paginate(:page => params[:page], :per_page => 30)
    if params[:search]
      @patients = Patient.where(id: params[:search]).paginate(:page => params[:page], :per_page => 30)
      if params[:search].blank?
        @patients = Patient.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
      end
    end
    respond_to do |f|
      f.html {
      }

      f.any(:xml, :json) {
        render request.format.to_sym => @patients
      }
    end
  end

  def destroy
    @patient = current_user.patients.find(params[:id])
    @patient.destroy

    redirect_to dashboard_path
  end

  def medicationindex
    @patient = current_user.patient.find(params[:id])
    @medications = @patient.medications
  end

  def importsearch
    @page_title = "Patients Index"
    @patients = Patient.where.not(:user_id => current_user).paginate(:page => params[:page], :per_page => 30)
    if params[:search]
      @patients = Patient.where.not(:user_id => current_user).where(:id => params[:search]).order("created_at DESC")
    else
      @patients = Patient.where.not(:user_id => current_user).order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
    end
  end

  def importpatient
    @page_title = 'Import Patient'
    @user = current_user
    @patient = Patient.find(params[:id])
    @patient.touch
    @patient.transfer(@user)
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :date_of_birth, :phone_number, :primary_care_physician, :user_id)
  end

end

app/helpers/patients_helper.rb
module PatientsHelper  
end

app/views/patients/_patientsindex.html.erb
<% if @patients.any? %>

  <% if @patients.where(updated_at: (Time.now - 24.hours)..Time.now).any? %>

    <% @patients.where(updated_at: (Time.now - 24.hours)..Time.now).each do |patient| %>
    <div class="hovertip"><%= link_to patient.name, user_patient_path(current_user, patient) %>
      <span class="hovertiptext"><%= patient.name %><br />
        Physician: <%= User.find(patient.user_id).name %><br />
        Age: <%= patient.find_age %> <br />
        Phone: <%= number_to_phone(patient.phone_number, area_code: true) %>
       </span>
    </div>
    <br />

    <% end %>

    <div class="digg_pagination">
      <%= will_paginate @patients %>
    </div>

  <% else %>
    <p>No Recent Patients</p>
  <% end %>

<% else %>

<p>No Patients yet.</p>

<% end %>

app/views/patients/adminindex.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>All Patients Index</h1>
  </div>
</div>

<% if @patients.any? %>

  <div class="container">
    <%= form_tag(patientindex_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Patients" %>
        <%= submit_tag "Search", :name => nil, :class => "btn btn-default"%>
    <% end %>
    <br />
  </div>

  <div class="container">
    <div class="page-header">
      <h3>Search Results</h3>
    </div>
  </div>

  <% @patients.each do |patient| %>

    <div class="hovertip"><%= link_to patient.name, user_patients_path(patient) %>
      <span class="hovertiptext"><%= patient.name %><br />
        Physician: <%= patient.user.name %><br />
        Age: <%= patient.find_age %> <br />
        Phone: <%= number_to_phone(patient.phone_number, area_code: true) %>
       </span>
    </div>
    <br />

  <% end %>

  <div class="digg_pagination">
    <%= will_paginate @patients %>
  </div>

<% else %>
  <% if params[:search] %>

    <div class="container">
      <div class="page-header">
        <h3>Search Results</h3>
      </div>
      <p>No patients could be found with the search "<%= params[:search] %>".</p>
    </div>

<% else %>

    <div class="container">
      <div class="page-header">
        <h3>No Patients</h3>
      </div>
      <p>
        No patients are registered in ChartPort yet!
      </p>
    </div>

  <% end %>

<% end %>

app/views/patients/edit.html.erb
<%= form_for :patient, url: user_patient_path(current_user, @patient), method: :patch do |f| %>

<div class="container">
  <div class="jumbotron">
    <h1>Edit Patient Record</h1>
    <hr />
    <h3>
      <%= @patient.name %>
    </h3>
  </div>
</div>

<div class="container">
  <div class="page-header">
    <h3>Patient Phone Number:</h3>
  </div>
  <%= f.telephone_field :phone_number, :class => 'textfield', value: number_to_phone(@patient.phone_number, area_code: true) %>
</div>
<br />

<%= button_tag(type: 'submit', class: "btn btn-default") do %>
 Update Record <span class="glyphicon glyphicon-floppy-disk"></span>
<% end %>


<% end %>

app/views/patients/importpatient.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Patient Records have been transferred.</h1>
    <hr />
    <p>You may now return to your <%= link_to "Dashboard", dashboard_path %>.</p>
  </div>
</div>

app/views/patients/importsearch.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Import Medical Records</h1>
  </div>
</div>

<% if @patients.any? %>

  <% if params[:search] %>

    <div class="container">
      <%= form_tag(importui_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Patients" %>
          <br />
          <br />
          <%= submit_tag "Search", :name => nil, :class => "btn btn-default"%>
      <% end %>
      <hr />
    </div>

    <div class="container">
      <h3>Results:</h3>

    <% @patients.each do |patient| %>

      <p>
        <%= link_to patient.name, user_patient_path(patient.user, patient) %>    <br />
          <small><%= User.find(patient.user_id).name %></small>
      </p>
    </div>

    <% end %>

    <div class="digg_pagination">
      <%= will_paginate @patients %>
    </div>

  <% else %>

    <div class="container">
      <%= form_tag(importui_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Patients" %>
          <br />
          <br />
          <%= submit_tag "Search", :name => nil, :class => "btn btn-default"%>
      <% end %>
      <hr />
    </div>

    <div class="container">
      <h3>Patients Available for Import</h3>

    <% @patients.each do |patient| %>

      <p>
        <%= link_to patient.name, user_patient_path(patient.user, patient) %>    <br />
          <small><%= User.find(patient.user_id).name %></small>
      </p>
    </div>

    <% end %>

    <div class="digg_pagination">
      <%= will_paginate @patients %>
    </div>

  <% end %>



<% else %>
  <div class="container">
    <div class="page-header">
      <h3>No Patients</h3>
    </div>
    <p>No Patients were found.</p>
  </div>

<% end %>

app/views/patients/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Your Patients Index</h1>
  </div>
</div>

<% if @patients.any? %>

<div class="container">
  <%= form_tag(user_patients_path(current_user), :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Patients" %>
      <%= submit_tag "Search", :name => nil, :class => "btn btn-default"%>
  <% end %>

  <%= button_to "New Patient Entry", new_user_patient_path, method: 'get', :class => "btn btn-default" %>
</div>

<br />

  <div class="container">
    <div class="page-header">
      <h3>Search Results</h3>
    </div>
  </div>

  <% @patients.each do |patient| %>

  <div class="hovertip"><%= link_to patient.name, user_patient_path(current_user, patient) %>
    <span class="hovertiptext"><%= patient.name %><br />
      Physician: <%= User.find(patient.user_id).name %><br />
      Age: <%= patient.find_age %> <br />
      Phone: <%= number_to_phone(patient.phone_number, area_code: true) %>
     </span>
  </div>
  <br />

  <% end %>

  <%= will_paginate @patients %>

<% else %>

  <% if !params[:search] %>
    <div class="page-header">
      <h3>No Patients Registered.</h3>
    </div>
    <p>
      You are not currently marked as the active doctor on any patients.
    </p>

  <% else %>

  <div class="container">
    <div class="page-header">
      <h3>Search Results</h3>
    </div>
    <p>No patients could be found with the search "<%= params[:search] %>".</p>
  </div>

  <% end %>

<% end %>

app/views/patients/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>New Patient Entry Form</h1>
  </div>
  <%= form_for @patient, url: user_patients_path(current_user) do |f| %>


  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient.errors.count, "error") %>
      </h2>
        <% @patient.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
    </div>
  <% end %>

  <div class="page-header">
    <h3><%= f.label "Patient Name" %></h3>
  </div>
  <p>
    <%= f.text_field :name, :class => 'textfield' %>
  </p>

  <div class="container-fluid">

    <div class="col-sm-6">
      <div class="page-header">
        <h3><%= f.label "Date of Birth" %></h3>
      </div>
      <p>
        <%= f.date_field :date_of_birth, :class => 'textfield', value: Time.now.strftime("%m/%d/%Y") %>
      </p>
    </div>

    <div class="col-sm-6">
      <div class="page-header">
        <h3><%= f.label "Phone Number" %></h3>
      </div>
      <p>
        <%= f.telephone_field :phone_number, :class => 'textfield', value: number_to_phone('1112223333', area_code: true) %>
      </p>
    </div>

  </div>

  <%= f.text_area :primary_care_physician, value: @user.id, style: "display: none;"  %>
  <br>
  <%= f.submit "Submit Patient" %>

  <% end %>

</div>

app/views/patients/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= @patient.name %></h1>
    <hr />
    <p>Primary Care Physician: <br />
      <%= link_to User.find(@patient.primary_care_physician).name, user_path(User.find(@patient.primary_care_physician)) %>
    </p>
    <% if @patient.primary_care_physician != @patient.user_id %>
    <p>
      Current Physician: <br />
      <%= link_to User.find(@patient.user_id).name, user_path(User.find(@patient.user_id)) %>
    </p>
    <% end %>
    <% if @patient.user_id == current_user.id %>
    <%= button_to "Edit Patient", edit_user_patient_path(current_user, @patient), method: 'get', :class => "btn btn-default" %>
    <% end %>
    <% if current_user.admin %>
      <button class="btn btn-default"><%= link_to 'Export JSON', controller: 'patients', action: 'show', format: 'json' %></button>
    <% end %>
    <% if @patient.user_id != current_user.id && !current_user.admin%>
      <%= button_to "Import Patient", :controller => 'patients', :action => "importpatient" %>
    <% end %>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="page-header">
        <h4>Patient Date of Birth:</h4>
      </div>
      <p><%= @patient.date_of_birth.to_date.strftime("%m/%d/%Y") %> (<%= @patient.find_age %> years old)</p>
    </div>
    <div class="col-sm-6">
      <div class="page-header">
        <h4>Patient Phone Number:</h4>
      </div>
      <p><%= number_to_phone(@patient.phone_number, area_code: true) %></p>
    </div>
  </div>
</div>

<div class="container">
  <div class="page-header">
    <h4>Patient Notes</h4>
  </div>
  <% if @patient.user_id == @current_user.id %>
    <button class="btn btn-default"><%= link_to "New Note", new_user_patient_patient_note_path(current_user, @patient) %>
      <i class="fa fa-plus"></i></button>
    <% end %>
  <%= render "patient_notes/index" %>
</div>


<div class="container">
  <div class="page-header">
    <h4>Medications</h4>
  </div>
  <% if @patient.user_id == @current_user.id && !current_user.admin %>
  <button class="btn-default"><%= link_to "Add Prescription", new_user_patient_medication_path(current_user, @patient) %>
  <i class="fa fa-medkit"></i></button>
  <% end %>
  <% if @patient.medications.any? %>
    <%= render 'medications/medicationindex' %>
  <% else %>
    <p>No known medications.</p>
  <% end %>
</div>